In [1]:
import pandas as pd
import numpy as np

## First people

In [35]:
#Importa los archivos
people = {}
people_names = [f'people1{i}.csv' for i in range(10)]
for name in people_names:
    people[name[:-4]] = pd.read_csv(f"datasets/People/{name}",engine= "python")

In [45]:
accidents = {}
for dataset_name in people:
    try:
        people[dataset_name] = people[dataset_name][["Codi districte","Nom districte"]]
        groupped = people[dataset_name].groupby("Codi districte").count()
    except:
        people[dataset_name] = people[dataset_name][["Codi_districte","Nom_districte"]]
        groupped = people[dataset_name].groupby("Codi_districte").count()
    
    groupped.columns = ["20" + dataset_name[-2:]]
    accidents[f"accidents{dataset_name[-2:]}"] = groupped

In [46]:
accidents["accidents14"] = accidents["accidents14"].drop("Desconegut")
accidents["accidents14"].index = [int(i) for i in accidents["accidents14"].index]

,accidents10,accidents11,accidents12,accidents13,accidents14,accidents15,accidents16,accidents17,accidents18,accidents19
,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
1,546,618,632,636,588.0,612,550,634,618,585
2,3011,2892,3195,3384,3429.0,3607,3760,3555,3566,3603
3,1075,1032,1198,1242,1243.0,1240,1338,1317,1240,1377
4,806,753,744,839,822.0,822,903,891,849,832
5,1257,1180,1323,1306,1270.0,1243,1231,1287,1323,1253
6,603,563,539,533,539.0,567,535,588,556,525
7,866,756,704,727,727.0,867,879,839,854,784
8,560,489,643,590,645.0,637,622,659,639,582
9,687,663,765,770,750.0,770,711,699,767,781
10,1377,1328,1303,1332,1345.0,1404,1528,1642,1438,1503

In [38]:
accidents_total = pd.concat(accidents, axis = 1).drop(-1)

In [47]:
accidents_total.head()

,accidents10,accidents11,accidents12,accidents13,accidents14,accidents15,accidents16,accidents17,accidents18,accidents19
,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
1,546,618,632,636,588.0,612,550,634,618,585
2,3011,2892,3195,3384,3429.0,3607,3760,3555,3566,3603
3,1075,1032,1198,1242,1243.0,1240,1338,1317,1240,1377
4,806,753,744,839,822.0,822,903,891,849,832
5,1257,1180,1323,1306,1270.0,1243,1231,1287,1323,1253

In [129]:
accidents_total["Codi_districte"] = district_index_ls

In [132]:
accidents_total.columns = ["201"+str(i) for i in range(10)] + ["Codi_districte"]

In [133]:
accidents_total

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,Codi_districte
1,546,618,632,636,588.0,612,550,634,618,585,1
2,3011,2892,3195,3384,3429.0,3607,3760,3555,3566,3603,2
3,1075,1032,1198,1242,1243.0,1240,1338,1317,1240,1377,3
4,806,753,744,839,822.0,822,903,891,849,832,4
5,1257,1180,1323,1306,1270.0,1243,1231,1287,1323,1253,5
6,603,563,539,533,539.0,567,535,588,556,525,6
7,866,756,704,727,727.0,867,879,839,854,784,7
8,560,489,643,590,645.0,637,622,659,639,582,8
9,687,663,765,770,750.0,770,711,699,767,781,9
10,1377,1328,1303,1332,1345.0,1404,1528,1642,1438,1503,10

In [134]:
abs_merge =accidents_total.merge(right = districts_codi, how = "left", on= "Codi_districte")

In [135]:
abs_merge

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,Codi_districte,Nom_districte
0,546,618,632,636,588.0,612,550,634,618,585,1,Ciutat Vella
1,3011,2892,3195,3384,3429.0,3607,3760,3555,3566,3603,2,Eixample
2,1075,1032,1198,1242,1243.0,1240,1338,1317,1240,1377,3,Sants-Montjuïc
3,806,753,744,839,822.0,822,903,891,849,832,4,Les Corts
4,1257,1180,1323,1306,1270.0,1243,1231,1287,1323,1253,5,Sarrià-Sant Gervasi
5,603,563,539,533,539.0,567,535,588,556,525,6,Gràcia
6,866,756,704,727,727.0,867,879,839,854,784,7,Horta-Guinardó
7,560,489,643,590,645.0,637,622,659,639,582,8,Nou Barris
8,687,663,765,770,750.0,770,711,699,767,781,9,Sant Andreu
9,1377,1328,1303,1332,1345.0,1404,1528,1642,1438,1503,10,Sant Martí

In [136]:
abs_new = abs_merge[["Nom_districte","2011","2012","2013","2014","2015","2016","2017","2018","2019"]].copy()

In [137]:
abs_new

         Nom_districte  2011  2012  2013    2014  2015  2016  2017  2018  2019
0         Ciutat Vella   618   632   636   588.0   612   550   634   618   585
1             Eixample  2892  3195  3384  3429.0  3607  3760  3555  3566  3603
2       Sants-Montjuïc  1032  1198  1242  1243.0  1240  1338  1317  1240  1377
3            Les Corts   753   744   839   822.0   822   903   891   849   832
4  Sarrià-Sant Gervasi  1180  1323  1306  1270.0  1243  1231  1287  1323  1253
5               Gràcia   563   539   533   539.0   567   535   588   556   525
6       Horta-Guinardó   756   704   727   727.0   867   879   839   854   784
7           Nou Barris   489   643   590   645.0   637   622   659   639   582
8          Sant Andreu   663   765   770   750.0   770   711   699   767   781
9           Sant Martí  1328  1303  1332  1345.0  1404  1528  1642  1438  1503

In [242]:
valores=pd.Series((abs_new["2019"]-abs_new["2011"])/abs_new["2011"]*100)

In [243]:
distritos=abs_new["Nom_districte"]

In [275]:
increment_10 = {"Nom_districte":distritos, "10y increment (%)":valores}
increment_10_df = pd.DataFrame(increment_10)

In [276]:
increment_10_df

         Nom_districte  10y increment (%)
0         Ciutat Vella          -5.339806
1             Eixample          24.585062
2       Sants-Montjuïc          33.430233
3            Les Corts          10.491368
4  Sarrià-Sant Gervasi           6.186441
5               Gràcia          -6.749556
6       Horta-Guinardó           3.703704
7           Nou Barris          19.018405
8          Sant Andreu          17.797888
9           Sant Martí          13.177711

In [277]:
increment_10_df_2 = pd.DataFrame(pd.DataFrame(increment_10_df).select_dtypes(exclude = object)).applymap(lambda x: round(x,2))

In [278]:
increment_10_df[list(increment_10_df.columns)[1:]]=increment_10_df_2

In [279]:
increment_10_df

         Nom_districte  10y increment (%)
0         Ciutat Vella              -5.34
1             Eixample              24.59
2       Sants-Montjuïc              33.43
3            Les Corts              10.49
4  Sarrià-Sant Gervasi               6.19
5               Gràcia              -6.75
6       Horta-Guinardó               3.70
7           Nou Barris              19.02
8          Sant Andreu              17.80
9           Sant Martí              13.18

In [246]:
def color_10years(val):
    """
    Takes a scalar and returns a string with
    the css property `'color: red'` for negative
    strings, black otherwise.
    """
      
    if val < 0:
        color = "green"
        
    elif 15 < val <20:
        color = "orange"

    elif val > 20:
        color = "red"

    else:
        color = "grey"

    return 'color: %s' % color

In [282]:
years_c = increment_10_df.style.applymap(color_10years, subset=pd.IndexSlice[:, ["10y increment (%)"]])
years_c

In [224]:
increment_10 = pd.DataFrame([abs_new["Nom_districte",(abs_new["2019"]-abs_new["2011"])])

SyntaxError: invalid syntax (<ipython-input-224-b64706a80e73>, line 1)

In [145]:
areas = pd.DataFrame({"Nom_districte" : ['Ciutat Vella','Eixample','Gràcia','Horta-Guinardó','Les Corts','Nou Barris','Sant Andreu','Sant Martí','Sants-Montjuïc','Sarrià-Sant Gervasi'],
                          "Areas" : [4.37,7.46,4.19,11.9,6.08,8.0,6.56,10.8,21.35,20.09]
                           })
areas

         Nom_districte  Areas
0         Ciutat Vella   4.37
1             Eixample   7.46
2               Gràcia   4.19
3       Horta-Guinardó  11.90
4            Les Corts   6.08
5           Nou Barris   8.00
6          Sant Andreu   6.56
7           Sant Martí  10.80
8       Sants-Montjuïc  21.35
9  Sarrià-Sant Gervasi  20.09

In [146]:
abs_area =abs_new.merge(right = areas, how = "left", on= "Nom_districte")

In [147]:
abs_area

,Nom_districte,2011,2012,2013,2014,2015,2016,2017,2018,2019,Areas
0,Ciutat Vella,618,632,636,588.0,612,550,634,618,585,4.37
1,Eixample,2892,3195,3384,3429.0,3607,3760,3555,3566,3603,7.46
2,Sants-Montjuïc,1032,1198,1242,1243.0,1240,1338,1317,1240,1377,21.35
3,Les Corts,753,744,839,822.0,822,903,891,849,832,6.08
4,Sarrià-Sant Gervasi,1180,1323,1306,1270.0,1243,1231,1287,1323,1253,20.09
5,Gràcia,563,539,533,539.0,567,535,588,556,525,4.19
6,Horta-Guinardó,756,704,727,727.0,867,879,839,854,784,11.90
7,Nou Barris,489,643,590,645.0,637,622,659,639,582,8.00
8,Sant Andreu,663,765,770,750.0,770,711,699,767,781,6.56
9,Sant Martí,1328,1303,1332,1345.0,1404,1528,1642,1438,1503,10.80

In [215]:
def color_absolutos(val):
    """
    Takes a scalar and returns a string with
    the css property `'color: red'` for negative
    strings, black otherwise.
    """
      
    if val < 600:
        color = "green"

    elif val > 1000:
        color = "red"

    else:
        color = "grey"

    return 'color: %s' % color

In [216]:
absolutos_c = abs_area.style.applymap(color_absolutos, subset=pd.IndexSlice[:, ['2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019']])
absolutos_c

In [157]:
abs_area[(list(abs_area.columns)[0])]

0           Ciutat Vella
1               Eixample
2         Sants-Montjuïc
3              Les Corts
4    Sarrià-Sant Gervasi
5                 Gràcia
6         Horta-Guinardó
7             Nou Barris
8            Sant Andreu
9             Sant Martí
Name: Nom_districte, dtype: object

In [163]:
rel_area = {}
for i in range(len(abs_area.columns)):
    if i == 0:
        rel_area[list(abs_area.columns)[i]] = abs_area[(list(abs_area.columns)[i])]
    else:
        rel_area[list(abs_area.columns)[i]] = (abs_area[(list(abs_area.columns)[i])])/(abs_area["Areas"])

In [168]:
rel_area_df = pd.DataFrame(rel_area)

In [170]:
rel_area_df.drop("Areas",axis=1)

,Nom_districte,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Ciutat Vella,141.418764,144.622426,145.537757,134.553776,140.045767,125.858124,145.080092,141.418764,133.867277
1,Eixample,387.667560,428.284182,453.619303,459.651475,483.512064,504.021448,476.541555,478.016086,482.975871
2,Sants-Montjuïc,48.337237,56.112412,58.173302,58.220141,58.079625,62.669789,61.686183,58.079625,64.496487
3,Les Corts,123.848684,122.368421,137.993421,135.197368,135.197368,148.519737,146.546053,139.638158,136.842105
4,Sarrià-Sant Gervasi,58.735689,65.853659,65.007466,63.215530,61.871578,61.274266,64.061722,65.853659,62.369338
5,Gràcia,134.367542,128.639618,127.207637,128.639618,135.322196,127.684964,140.334129,132.696897,125.298329
6,Horta-Guinardó,63.529412,59.159664,61.092437,61.092437,72.857143,73.865546,70.504202,71.764706,65.882353
7,Nou Barris,61.125000,80.375000,73.750000,80.625000,79.625000,77.750000,82.375000,79.875000,72.750000
8,Sant Andreu,101.067073,116.615854,117.378049,114.329268,117.378049,108.384146,106.554878,116.920732,119.054878
9,Sant Martí,122.962963,120.648148,123.333333,124.537037,130.000000,141.481481,152.037037,133.148148,139.166667

In [188]:
rel_area_df_2 = pd.DataFrame(pd.DataFrame(rel_area).select_dtypes(exclude = object)).applymap(lambda x: round(x,2))

In [191]:
rel_area_df[list(rel_area_df.columns)[1:]]=rel_area_df_2

In [192]:
rel_area_df

,Nom_districte,2011,2012,2013,2014,2015,2016,2017,2018,2019,Areas
0,Ciutat Vella,141.42,144.62,145.54,134.55,140.05,125.86,145.08,141.42,133.87,1.0
1,Eixample,387.67,428.28,453.62,459.65,483.51,504.02,476.54,478.02,482.98,1.0
2,Sants-Montjuïc,48.34,56.11,58.17,58.22,58.08,62.67,61.69,58.08,64.50,1.0
3,Les Corts,123.85,122.37,137.99,135.20,135.20,148.52,146.55,139.64,136.84,1.0
4,Sarrià-Sant Gervasi,58.74,65.85,65.01,63.22,61.87,61.27,64.06,65.85,62.37,1.0
5,Gràcia,134.37,128.64,127.21,128.64,135.32,127.68,140.33,132.70,125.30,1.0
6,Horta-Guinardó,63.53,59.16,61.09,61.09,72.86,73.87,70.50,71.76,65.88,1.0
7,Nou Barris,61.12,80.38,73.75,80.62,79.62,77.75,82.38,79.88,72.75,1.0
8,Sant Andreu,101.07,116.62,117.38,114.33,117.38,108.38,106.55,116.92,119.05,1.0
9,Sant Martí,122.96,120.65,123.33,124.54,130.00,141.48,152.04,133.15,139.17,1.0

In [203]:
rel_area_df_new=rel_area_df.drop("Areas",axis=1)

In [204]:
rel_area_df_new

,Nom_districte,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Ciutat Vella,141.42,144.62,145.54,134.55,140.05,125.86,145.08,141.42,133.87
1,Eixample,387.67,428.28,453.62,459.65,483.51,504.02,476.54,478.02,482.98
2,Sants-Montjuïc,48.34,56.11,58.17,58.22,58.08,62.67,61.69,58.08,64.50
3,Les Corts,123.85,122.37,137.99,135.20,135.20,148.52,146.55,139.64,136.84
4,Sarrià-Sant Gervasi,58.74,65.85,65.01,63.22,61.87,61.27,64.06,65.85,62.37
5,Gràcia,134.37,128.64,127.21,128.64,135.32,127.68,140.33,132.70,125.30
6,Horta-Guinardó,63.53,59.16,61.09,61.09,72.86,73.87,70.50,71.76,65.88
7,Nou Barris,61.12,80.38,73.75,80.62,79.62,77.75,82.38,79.88,72.75
8,Sant Andreu,101.07,116.62,117.38,114.33,117.38,108.38,106.55,116.92,119.05
9,Sant Martí,122.96,120.65,123.33,124.54,130.00,141.48,152.04,133.15,139.17

In [199]:
print(rel_area_df.min(),
rel_area_df.max(),
rel_area_df.mean(),
rel_area_df.median())

Nom_districte    Ciutat Vella
2011                    48.34
2012                    56.11
2013                    58.17
2014                    58.22
2015                    58.08
2016                    61.27
2017                    61.69
2018                    58.08
2019                    62.37
Areas                       1
dtype: object Nom_districte    Sarrià-Sant Gervasi
2011                          387.67
2012                          428.28
2013                          453.62
2014                          459.65
2015                          483.51
2016                          504.02
2017                          476.54
2018                          478.02
2019                          482.98
Areas                              1
dtype: object 2011     124.307
2012     132.268
2013     136.309
2014     136.006
2015     141.389
2016     143.150
2017     144.572
2018     141.742
2019     140.271
Areas      1.000
dtype: float64 2011     112.015
2012     118.635
2013     120.355
2014     119.435
2015     123.690
2016     117.120
2017     123.440
2018     124.810
2019     122.175
Areas      1.000
dtype: float64

In [211]:
def color_area(val):
    """
    Takes a scalar and returns a string with
    the css property `'color: red'` for negative
    strings, black otherwise.
    """
      
    if val < 80:
        color = "green"

    elif 130 < val < 250:
        color = "orange"

    elif val > 250:
        color = "red"

    else:
        color = "grey"

    return 'color: %s' % color

In [212]:
area_c = rel_area_df_new.style.applymap(color_area, subset=pd.IndexSlice[:, ['2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019']])
area_c

In [254]:
people_final = accidents_total

In [259]:
percentage = {}
for i in range(len(people_final.columns)):
    if i != list(range(len(people_final.columns)))[-1]:
        percentage[list(people_final.columns)[i + 1]] = ((people_final[(list(people_final.columns)[i + 1])] - 
                   people_final[(list(people_final.columns)[i])]) / 
                   people_final[(list(people_final.columns)[i])] * 100)

In [260]:
result=pd.DataFrame(percentage).applymap(lambda x: round(x,2))

In [263]:
result

,2011,2012,2013,2014,2015,2016,2017,2018,2019,Codi_districte
1,13.19,2.27,0.63,-7.55,4.08,-10.13,15.27,-2.52,-5.34,1
2,-3.95,10.48,5.92,1.33,5.19,4.24,-5.45,0.31,1.04,2
3,-4.00,16.09,3.67,0.08,-0.24,7.90,-1.57,-5.85,11.05,3
4,-6.58,-1.20,12.77,-2.03,0.00,9.85,-1.33,-4.71,-2.00,4
5,-6.13,12.12,-1.28,-2.76,-2.13,-0.97,4.55,2.80,-5.29,5
6,-6.63,-4.26,-1.11,1.13,5.19,-5.64,9.91,-5.44,-5.58,6
7,-12.70,-6.88,3.27,0.00,19.26,1.38,-4.55,1.79,-8.20,7
8,-12.68,31.49,-8.24,9.32,-1.24,-2.35,5.95,-3.03,-8.92,8
9,-3.49,15.38,0.65,-2.60,2.67,-7.66,-1.69,9.73,1.83,9
10,-3.56,-1.88,2.23,0.98,4.39,8.83,7.46,-12.42,4.52,10

In [151]:
def color_negative_red(val):
    """
    Takes a scalar and returns a string with
    the css property `'color: red'` for negative
    strings, black otherwise.
    """
    color = 'black' if val > 0 else 'black'
    return 'color: %s' % color

In [122]:
def color_negative_green(val):
    """
    Takes a scalar and returns a string with
    the css property `'color: red'` for negative
    strings, black otherwise.
    """
      
    if val < -10:
        color = "green"

    elif 5 < val < 10:
        color = "orange"

    elif val > 10:
        color = "red"

    else:
        color = "grey"

    return 'color: %s' % color

In [120]:
def color_negative_green(val):
    """
    Takes a scalar and returns a string with
    the css property `'color: red'` for negative
    strings, black otherwise.
    """
    if type(value) != int:
        return value
        
    else:
        if val < -10:
            color = "green"

        elif 5 < val < 10:
            color = "orange"

        elif val > 10:
            color = "red"

        else:
            color = "grey"

        return 'color: %s' % color

In [269]:
result_c = result_new.style.applymap(color_negative_green, subset=pd.IndexSlice[:, ['2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019']])
result_c

In [125]:
result_c = result.style.applymap(color_negative_green)
result_c

In [66]:
district_index= {"Codi_districte":[1,2,3,4,5,6,7,8,9,10]}

In [68]:
district_index_ls= [1,2,3,4,5,6,7,8,9,10]

In [262]:
result["Codi_districte"] = district_index_ls

In [97]:
result.columns = ["201"+str(i) for i in range(1,10)] + ["Codi_districte"]

In [258]:
result.head()

    2011   2012   2013  2014  2015   2016   2017  2018  2019  Codi_districte
1  11.65   2.22   0.63 -8.16  3.92 -11.27  13.25 -2.59 -5.64        -58400.0
2  -4.11   9.48   5.59  1.31  4.93   4.07  -5.77  0.31  1.03       -180050.0
3  -4.17  13.86   3.54  0.08 -0.24   7.32  -1.59 -6.21  9.95        -45800.0
4  -7.04  -1.21  11.32 -2.07  0.00   8.97  -1.35 -4.95 -2.04        -20700.0
5  -6.53  10.81  -1.30 -2.83 -2.17  -0.97   4.35  2.72 -5.59        -24960.0

In [91]:
result.columns

Index(['2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019'],
      dtype='object')

In [60]:
districts=pd.read_csv(f"datasets/People/people19.csv")

In [61]:
districts.columns

Index(['Numero_Expedient', 'Codi_districte', 'Nom_districte', 'Codi_barri',
       'Nom_barri', 'Codi_carrer', 'Num_postal', 'Num_postal.1',
       'Descripcio_dia_setmana', 'Dia_setmana', 'Descripcio_tipus_dia',
       'NK_ Any', 'Mes_ any', 'Nom_mes', 'Dia_mes', 'Descripcio_torn',
       'Hora_dia', 'Descripcio_causa_vianant', 'Desc_Tipus_vehicle_implicat',
       'Descripcio_sexe', 'Edat', 'Descripcio_tipus_persona',
       'Descripcio_Lloc_atropellament_vianat',
       'Descripcio_Motiu_desplaçament_vianant',
       'Descripcio_Motiu_desplaçament_conductor', 'Descripcio_victimitzacio',
       'Coordenada_UTM_X', 'Coordenada_UTM_Y', 'Longitud', 'Latitud'],
      dtype='object')

In [62]:
districts_num = districts[["Codi_districte","Nom_districte"]]

In [63]:
districts_num.head()

   Codi_districte        Nom_districte
0               5  Sarrià-Sant Gervasi
1               5  Sarrià-Sant Gervasi
2               5  Sarrià-Sant Gervasi
3               4            Les Corts
4               4            Les Corts

In [64]:
districts_codi=districts_num.drop_duplicates(subset="Codi_districte")

In [65]:
districts_codi

      Codi_districte        Nom_districte
0                  5  Sarrià-Sant Gervasi
3                  4            Les Corts
63                 3       Sants-Montjuïc
152               -1           Desconegut
277                7       Horta-Guinardó
485                6               Gràcia
1402               2             Eixample
2957               8           Nou Barris
3197               1         Ciutat Vella
4605              10           Sant Martí
4668               9          Sant Andreu

In [264]:
result_merge = result.merge(right = districts_codi, how = "left", on= "Codi_districte")

In [265]:
result_merge.columns

Index(['2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       'Codi_districte', 'Nom_districte'],
      dtype='object')

In [266]:
result_merge

,2011,2012,2013,2014,2015,2016,2017,2018,2019,Codi_districte,Nom_districte
0,13.19,2.27,0.63,-7.55,4.08,-10.13,15.27,-2.52,-5.34,1,Ciutat Vella
1,-3.95,10.48,5.92,1.33,5.19,4.24,-5.45,0.31,1.04,2,Eixample
2,-4.00,16.09,3.67,0.08,-0.24,7.90,-1.57,-5.85,11.05,3,Sants-Montjuïc
3,-6.58,-1.20,12.77,-2.03,0.00,9.85,-1.33,-4.71,-2.00,4,Les Corts
4,-6.13,12.12,-1.28,-2.76,-2.13,-0.97,4.55,2.80,-5.29,5,Sarrià-Sant Gervasi
5,-6.63,-4.26,-1.11,1.13,5.19,-5.64,9.91,-5.44,-5.58,6,Gràcia
6,-12.70,-6.88,3.27,0.00,19.26,1.38,-4.55,1.79,-8.20,7,Horta-Guinardó
7,-12.68,31.49,-8.24,9.32,-1.24,-2.35,5.95,-3.03,-8.92,8,Nou Barris
8,-3.49,15.38,0.65,-2.60,2.67,-7.66,-1.69,9.73,1.83,9,Sant Andreu
9,-3.56,-1.88,2.23,0.98,4.39,8.83,7.46,-12.42,4.52,10,Sant Martí

In [267]:
result_new = result_merge[["Nom_districte","2011","2012","2013","2014","2015","2016","2017","2018","2019"]].copy()

In [268]:
result_new

,Nom_districte,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Ciutat Vella,13.19,2.27,0.63,-7.55,4.08,-10.13,15.27,-2.52,-5.34
1,Eixample,-3.95,10.48,5.92,1.33,5.19,4.24,-5.45,0.31,1.04
2,Sants-Montjuïc,-4.00,16.09,3.67,0.08,-0.24,7.90,-1.57,-5.85,11.05
3,Les Corts,-6.58,-1.20,12.77,-2.03,0.00,9.85,-1.33,-4.71,-2.00
4,Sarrià-Sant Gervasi,-6.13,12.12,-1.28,-2.76,-2.13,-0.97,4.55,2.80,-5.29
5,Gràcia,-6.63,-4.26,-1.11,1.13,5.19,-5.64,9.91,-5.44,-5.58
6,Horta-Guinardó,-12.70,-6.88,3.27,0.00,19.26,1.38,-4.55,1.79,-8.20
7,Nou Barris,-12.68,31.49,-8.24,9.32,-1.24,-2.35,5.95,-3.03,-8.92
8,Sant Andreu,-3.49,15.38,0.65,-2.60,2.67,-7.66,-1.69,9.73,1.83
9,Sant Martí,-3.56,-1.88,2.23,0.98,4.39,8.83,7.46,-12.42,4.52

In [105]:
ls = []
for i in range(len(people_final.columns)):
    ls.append(people_final[(list(people_final.columns)[i + 1]) - people_final[list(people_final.columns)[i]] / 
                           people_final[list(people_final.columns)[i + 1]]])

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')

In [101]:
(618 - 546) / 618 * 100

11.650485436893204

## Second vehicles

In [18]:
vehic10 = pd.read_csv("datasets/Vehicles/vehicle10.csv",engine= "python")
vehic11 = pd.read_csv("datasets/Vehicles/vehicle11.csv",engine= "python")
vehic12 = pd.read_csv("datasets/Vehicles/vehicle12.csv",engine= "python")
vehic13 = pd.read_csv("datasets/Vehicles/vehicle13.csv",engine= "python")
vehic14 = pd.read_csv("datasets/Vehicles/vehicle14.csv",engine= "python")
vehic15 = pd.read_csv("datasets/Vehicles/vehicle15.csv",engine= "python")
vehic16 = pd.read_csv("datasets/Vehicles/vehicle16.csv",engine= "python")
vehic17 = pd.read_csv("datasets/Vehicles/vehicle17.csv",engine= "python")
vehic18 = pd.read_csv("datasets/Vehicles/vehicle18.csv",engine= "python")
vehic19 = pd.read_csv("datasets/Vehicles/vehicle19.csv",engine= "python")

In [23]:
vehic10_sub = vehic10[["Codi districte","Nom districte"]]
vehic11_sub = vehic11[["Codi districte","Nom districte"]]
vehic12_sub = vehic12[["Codi districte","Nom districte"]]
vehic13_sub = vehic13[["Codi districte","Nom districte"]]
vehic14_sub = vehic14[["Codi districte","Nom districte"]]
vehic15_sub = vehic15[["Codi districte","Nom districte"]]
vehic16_sub = vehic16[["Codi_districte","Nom_districte"]]
vehic17_sub = vehic17[["Codi_districte","Nom_districte"]]
vehic18_sub = vehic18[["Codi_districte","Nom_districte"]]
vehic19_sub = vehic19[["Codi_districte","Nom_districte"]]

In [27]:
accidents_vehic_10 = vehic10_sub.groupby("Codi districte").count()
accidents_vehic_10.columns = ["2010"]
accidents_vehic_11 = vehic11_sub.groupby("Codi districte").count()
accidents_vehic_11.columns = ["2011"]
accidents_vehic_12 = vehic12_sub.groupby("Codi districte").count()
accidents_vehic_12.columns = ["2012"]
accidents_vehic_13 = vehic13_sub.groupby("Codi districte").count()
accidents_vehic_13.columns = ["2013"]
accidents_vehic_14 = vehic14_sub.groupby("Codi districte").count()
accidents_vehic_14.columns = ["2014"]
accidents_vehic_15 = vehic15_sub.groupby("Codi districte").count()
accidents_vehic_15.columns = ["2015"]
accidents_vehic_16 = vehic16_sub.groupby("Codi_districte").count()
accidents_vehic_16.columns = ["2016"]
accidents_vehic_17 = vehic17_sub.groupby("Codi_districte").count()
accidents_vehic_17.columns = ["2017"]
accidents_vehic_18 = vehic18_sub.groupby("Codi_districte").count()
accidents_vehic_18.columns = ["2018"]
accidents_vehic_19 = vehic19_sub.groupby("Codi_districte").count()
accidents_vehic_19.columns = ["2019"]

In [49]:
accidents_vehic_total = pd.concat([accidents_vehic_10,accidents_vehic_11,accidents_vehic_12, accidents_vehic_13,accidents_vehic_14,accidents_vehic_15,accidents_vehic_16,accidents_vehic_17,accidents_vehic_18,accidents_vehic_19], axis = 1)

In [59]:
accidents_vehic_10.index = [int(i) for i in accidents_10.index]
accidents_vehic_11.index = [int(i) for i in accidents_11.index]
accidents_vehic_12.index = [int(i) for i in accidents_12.index]
accidents_vehic_13.index = [int(i) for i in accidents_13.index]
accidents_vehic_14.index = [int(i) for i in accidents_14.index]

ValueError: Length mismatch: Expected axis has 11 elements, new values have 10 elements

In [50]:
accidents_vehic_total

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
-1,NaN,NaN,NaN,NaN,NaN,19.0,21.0,50.0,NaN,34.0
1,NaN,NaN,NaN,NaN,NaN,1017.0,920.0,1034.0,966.0,986.0
2,NaN,NaN,NaN,NaN,NaN,5935.0,6097.0,5902.0,5763.0,5787.0
3,NaN,NaN,NaN,NaN,NaN,2020.0,2102.0,2109.0,1999.0,2198.0
4,NaN,NaN,NaN,NaN,NaN,1363.0,1455.0,1392.0,1325.0,1289.0
5,NaN,NaN,NaN,NaN,NaN,2156.0,2084.0,2195.0,2141.0,2052.0
6,NaN,NaN,NaN,NaN,NaN,926.0,909.0,975.0,875.0,850.0
7,NaN,NaN,NaN,NaN,NaN,1355.0,1363.0,1397.0,1377.0,1204.0
8,NaN,NaN,NaN,NaN,NaN,962.0,961.0,1050.0,1041.0,979.0
9,NaN,NaN,NaN,NaN,NaN,1226.0,1059.0,1097.0,1263.0,1209.0
10,NaN,NaN,NaN,NaN,NaN,2258.0,2439.0,2594.0,2329.0,2449.0
1,847.0,1012.0,1010.0,993.0,927.0,NaN,NaN,NaN,NaN,NaN
10,2171.0,2125.0,2129.0,2115.0,2256.0,NaN,NaN,NaN,NaN,NaN
2,4872.0,4690.0,5185.0,5437.0,5660.0,NaN,NaN,NaN,NaN,NaN
3,1831.0,1750.0,1948.0,2000.0,1970.0,NaN,NaN,NaN,NaN,NaN
4,1243.0,1224.0,1218.0,1382.0,1345.0,NaN,NaN,NaN,NaN,NaN
5,2027.0,1982.0,2184.0,2116.0,2168.0,NaN,NaN,NaN,NaN,NaN
6,971.0,921.0,882.0,858.0,899.0,NaN,NaN,NaN,NaN,NaN
7,1416.0,1229.0,1198.0,1201.0,1187.0,NaN,NaN,NaN,NaN,NaN
8,929.0,798.0,1035.0,939.0,988.0,NaN,NaN,NaN,NaN,NaN
9,1042.0,1036.0,1134.0,1204.0,1167.0,NaN,NaN,NaN,NaN,NaN
Desconegut,33.0,36.0,36.0,38.0,37.0,NaN,NaN,NaN,NaN,NaN

In [56]:
vehic_final = accidents_vehic_total.iloc[1:]

In [57]:
vehic_final = vehic_final.iloc[:-1]

In [58]:
vehic_final

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
1,NaN,NaN,NaN,NaN,NaN,1017.0,920.0,1034.0,966.0,986.0
2,NaN,NaN,NaN,NaN,NaN,5935.0,6097.0,5902.0,5763.0,5787.0
3,NaN,NaN,NaN,NaN,NaN,2020.0,2102.0,2109.0,1999.0,2198.0
4,NaN,NaN,NaN,NaN,NaN,1363.0,1455.0,1392.0,1325.0,1289.0
5,NaN,NaN,NaN,NaN,NaN,2156.0,2084.0,2195.0,2141.0,2052.0
6,NaN,NaN,NaN,NaN,NaN,926.0,909.0,975.0,875.0,850.0
7,NaN,NaN,NaN,NaN,NaN,1355.0,1363.0,1397.0,1377.0,1204.0
8,NaN,NaN,NaN,NaN,NaN,962.0,961.0,1050.0,1041.0,979.0
9,NaN,NaN,NaN,NaN,NaN,1226.0,1059.0,1097.0,1263.0,1209.0
10,NaN,NaN,NaN,NaN,NaN,2258.0,2439.0,2594.0,2329.0,2449.0
1,847.0,1012.0,1010.0,993.0,927.0,NaN,NaN,NaN,NaN,NaN
10,2171.0,2125.0,2129.0,2115.0,2256.0,NaN,NaN,NaN,NaN,NaN
2,4872.0,4690.0,5185.0,5437.0,5660.0,NaN,NaN,NaN,NaN,NaN
3,1831.0,1750.0,1948.0,2000.0,1970.0,NaN,NaN,NaN,NaN,NaN
4,1243.0,1224.0,1218.0,1382.0,1345.0,NaN,NaN,NaN,NaN,NaN
5,2027.0,1982.0,2184.0,2116.0,2168.0,NaN,NaN,NaN,NaN,NaN
6,971.0,921.0,882.0,858.0,899.0,NaN,NaN,NaN,NaN,NaN
7,1416.0,1229.0,1198.0,1201.0,1187.0,NaN,NaN,NaN,NaN,NaN
8,929.0,798.0,1035.0,939.0,988.0,NaN,NaN,NaN,NaN,NaN
9,1042.0,1036.0,1134.0,1204.0,1167.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
accidents_14.index = [int(i) for i in accidents_14.index]